services:
  conectar-postgres:
    image: postgres:latest
    container_name: conectar-postgres
    hostname: conectar-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=conectar_system
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d conectar_system']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - '5432:5432'
    networks:
      - conectar-network
networks:
  conectar-network:
    driver: bridge
